export const PASSIVE_STAGES = [
  ["validate", "Validating URL"],
  ["dns", "Resolving DNS"],
  ["surface", "Discovering attack surface"],
  ["crawl", "Crawling website"],
  ["hidden-surface", "Discovering hidden routes"],
  ["tls", "Testing TLS"],
  ["headers", "Testing headers"],
  ["cookies", "Testing cookies"],
  ["cors", "Testing CORS"],
  ["csp", "Testing CSP"],
  ["adaptive-differential", "Running adaptive differential probes"],
  ["manual-review", "Prioritising manual review"],
  ["external-scanners", "Running external scanners"],
  ["passive", "Running passive scanning"],
  ["correlate", "Correlating findings"],
  ["score", "Calculating scores"],
  ["report", "Generating report"],
] as const;
