export const PASSIVE_STAGES = [
  ["validate", "Validating URL"],
  ["dns", "Resolving DNS"],
  ["surface", "Discovering attack surface"],
  ["auth-verify", "Verifying authenticated access"],
  ["crawl", "Crawling website"],
  ["browser-render", "Rendering JavaScript surface"],
  ["role-compare", "Comparing role access"],
  ["evasion", "Detecting evasion signals"],
  ["exposure-probes", "Checking exposed sensitive files"],
  ["hidden-surface", "Discovering hidden routes"],
  ["tls", "Testing TLS"],
  ["headers", "Testing headers"],
  ["cookies", "Testing cookies"],
  ["cors", "Testing CORS"],
  ["csp", "Testing CSP"],
  ["adaptive-differential", "Running adaptive differential probes"],
  ["api-specific", "Testing API-specific controls"],
  ["manual-review", "Prioritising manual review"],
  ["external-scanners", "Running external scanners"],
  ["passive", "Running passive scanning"],
  ["correlate", "Correlating findings"],
  ["score", "Calculating scores"],
  ["report", "Generating report"],
] as const;
